#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# 测试脚本转换器
#
# 职责：将 Playwright codegen 原始脚本转换为 healer 兼容格式，
# 支持 page→healing_page 替换、类型注解清理、断言桩注入、
# 变量提取桩注入（{{variable}} 模板语法）。
# 替换过程使用占位符保护机制防止双重替换。

import re
from pathlib import Path
from typing import List, Optional, Dict


class HealingScriptTransformer:
    """将 codegen 生成的脚本转换为 healer 兼容格式"""

    def transform(
        self,
        input_path: str,
        output_path: str,
        module_name: str = "",
        extract_vars: Optional[List[Dict]] = None,
        assert_stubs: Optional[List[Dict]] = None,
    ) -> str:
        """转换脚本

        Args:
            input_path: codegen 生成的原始脚本路径
            output_path: 转换后的增强脚本路径
            module_name: 模块名称
            extract_vars: 变量提取桩列表
            assert_stubs: 断言桩列表

        Returns:
            str: 转换后的脚本内容
        """
        with open(input_path, 'r', encoding='utf-8') as f:
            source = f.read()

        # 用占位符保护已替换的内容，避免双重替换
        PLACEHOLDER = "\x00HEALING_PAGE\x00"

        # 1. 替换函数签名中的 page 参数
        #    def test_xxx(page: Page) → def test_xxx(healing_page)
        source = re.sub(
            r'def (test_\w+)\(\s*page(?:\s*:\s*Page)?\s*\)',
            rf'def \1({PLACEHOLDER})',
            source,
        )

        # 2. 替换 expect(page) → expect(PLACEHOLDER)
        source = re.sub(r'\bexpect\(page\)', rf'expect({PLACEHOLDER})', source)
        source = re.sub(r'\bexpect\(page\b', rf'expect({PLACEHOLDER}', source)

        # 3. 替换 page.xxx 操作调用 → PLACEHOLDER.xxx（核心替换）
        #    只匹配 \bpage\. 避免匹配 import 中的 Page
        source = re.sub(r'\bpage\.', f'{PLACEHOLDER}.', source)

        # 4. 删除 page = context.new_page() 行
        source = re.sub(r'\s*page\s*=\s*context\.new_page\(\).*\n?', '', source)

        # 5. 处理 import 行：移除 Page 类型，保留其他 import
        def _fix_import_line(match):
            """处理 from playwright.sync_api import ... 这行"""
            full_line = match.group(0)
            # 提取 import 列表
            import_match = re.search(r'from\s+playwright\.sync_api\s+import\s+(.*)', full_line)
            if not import_match:
                return ''
            imports_str = import_match.group(1)
            # 分割各个 import 项
            items = [i.strip() for i in imports_str.split(',')]
            # 移除 Page
            items = [i for i in items if i and i != 'Page']
            if not items:
                return ''
            return f'from playwright.sync_api import {", ".join(items)}\n'

        source = re.sub(
            r'from\s+playwright\.sync_api\s+import\s+.*?Page.*?\n',
            _fix_import_line,
            source,
            count=1,
        )

        # 6. 现在安全地把占位符替换为 healing_page
        source = source.replace(PLACEHOLDER, 'healing_page')

        # 6a. 表单填写经验沉淀 — 自动优化常见问题
        source = self._apply_form_experience(source)

        # 6b. 注入 context/browser 别名（codegen 脚本可能引用这些变量）
        # healing_page 实际上就是一个 Page 对象，没有 context/browser
        # 如果脚本中有 context.xxx 或 browser.xxx 的调用，需要提供别名
        has_context_ref = bool(re.search(r'\bcontext\.', source))
        has_browser_ref = bool(re.search(r'\bbrowser\.', source))
        if has_context_ref or has_browser_ref:
            alias_inject = ""
            if has_context_ref:
                alias_inject += "    context = healing_page.context\n"
            if has_browser_ref:
                alias_inject += "    browser = healing_page.context.browser\n"
            # 注入到 def test_xxx(healing_page): 下一行
            source = re.sub(
                r'(def test_\w+\(healing_page\)\s*:\n)',
                rf'\1{alias_inject}',
                source,
                count=1,
            )

        # 7. 注入模块头部说明
        # 在头部插入 import datetime（用于时间戳变量）
        ts_import = "from datetime import datetime\n"
        # 在 def test_xxx 之前插入时间戳变量定义
        ts_var = '    _test_ts = datetime.now().strftime("%Y%m%d%H%M%S")\n'

        header = f'''"""
Auto-generated by smart-test-automation
Module: {module_name}
Self-healing enabled via playwright-healer (healing_page fixture)

Run with:
    pytest {Path(output_path).name} --ph-strategy=SMART --ph-auto-patch-source
"""

'''
        # 删除原始文件的 docstring（如果有）
        source = re.sub(r'^""".*?"""', '', source, count=1, flags=re.DOTALL)
        source = header + source.strip() + '\n'

        # 7b. 在 import 区域后插入 datetime import
        # 找到最后一个 import 行，在其后插入
        import_lines = list(re.finditer(r'^(?:from\s+[\w.]+\s+import\s+.*|import\s+.*)$', source, re.MULTILINE))
        if import_lines:
            last_import = import_lines[-1]
            source = source[:last_import.end()] + '\n' + ts_import + source[last_import.end():]

        # 7c. 在 def test_xxx(healing_page): 后插入时间戳变量
        source = re.sub(
            r'(def test_\w+\(healing_page\)(?:\s*->\s*[^:]+)?\s*:\n)',
            rf'\1{ts_var}',
            source,
            count=1,
        )

        # 8. 收集所有要注入的代码块，然后一次性注入（避免多次插入位置错乱）
        injection_blocks = []

        # 8a. 变量提取桩
        if extract_vars:
            extract_block = "    # === 变量提取 ===\n"
            extract_block += "    extracted_vars = {}\n"
            for var in extract_vars:
                var_name = var.get("name", "")
                from_api = var.get("from_api", "")
                from_field = var.get("from_field", "")
                extract_block += f"    # TODO: extracted_vars['{var_name}'] = 从API响应提取 ({from_api}.{from_field})\n"
            extract_block += "    # 变量将在编排引擎中自动注入到后续模块\n"
            injection_blocks.append(extract_block)

        # 8b. 断言桩
        assert_block = "    # === 三层断言 ===\n"
        if assert_stubs:
            for stub in assert_stubs:
                layer = stub.get("layer", "ui")
                desc = stub.get("description", "")
                if layer == "ui":
                    assert_block += f"    # UI断言: {desc}\n"
                    assert_block += f"    # expect(healing_page.get_by_text('{desc}')).to_be_visible()\n"
                elif layer == "api":
                    assert_block += f"    # API断言: {desc}\n"
                    assert_block += f"    # assert api_response['code'] == 0\n"
                elif layer == "db":
                    assert_block += f"    # DB断言: {desc}\n"
                    assert_block += f"    # assert db_query_result is not None\n"
        else:
            assert_block += "    # UI断言: 操作成功提示可见\n"
            assert_block += "    # expect(healing_page.get_by_text('成功')).to_be_visible()\n"
            assert_block += "    # API断言: 关键接口返回 code=0\n"
            assert_block += "    # DB断言: 数据记录已写入（MySQL不可达则跳过）\n"
        injection_blocks.append(assert_block)

        # 一次性在最后一个 healing_page.xxx 操作行之后注入所有代码块
        source = self._inject_after_last_action(source, '\n'.join(injection_blocks))

        # 9. 保存未清洗版本（完整版，调试用）
        output_dir = Path(output_path).parent
        output_dir.mkdir(parents=True, exist_ok=True)
        raw_enhanced_path = output_dir / "enhanced_script_raw.py"
        raw_enhanced_path.write_text(source, encoding='utf-8')

        # 10. 清洗录制噪音（生成精简版）
        source = self._clean_noise(source)

        # 11. 写入精简版输出文件
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(source)

        print(f"✅ 转换完成: {input_path} → {output_path}")
        print(f"   完整版备份: {raw_enhanced_path}")
        return source

    def generate_po_layers(
        self,
        enhanced_script_path: str,
        output_dir: str,
        module_name: str,
        page_class_name: str = "",
    ) -> Dict[str, str]:
        """将 enhanced_script 拆分为 PO 三层结构

        生成:
          - base_page.py: BasePage 基础类（封装 healing_page 常用操作）
          - {module}_page.py: 业务 Page 类（封装业务操作方法）
          - test_{module}.py: pytest 用例（调用业务 Page）

        Args:
            enhanced_script_path: enhanced_script.py 路径
            output_dir: 输出目录
            module_name: 模块名
            page_class_name: 自定义 Page 类名（默认 CamelCase 转换）

        Returns:
            Dict[str, str]: 生成的文件路径
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # 读取 enhanced_script 提取操作
        with open(enhanced_script_path, 'r', encoding='utf-8') as f:
            source = f.read()

        # 提取 healing_page 操作行
        operations = []
        for line in source.split('\n'):
            stripped = line.strip()
            if stripped.startswith('healing_page.') and not stripped.startswith('#'):
                operations.append(stripped)

        if not page_class_name:
            page_class_name = self._to_camel_case(module_name) + "Page"

        # ===== 1. BasePage =====
        base_page_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BasePage — 页面基础类

封装 healing_page 常用操作，所有业务 Page 类继承此类。
自愈功能由 playwright-healer 的 healing_page fixture 自动提供。
"""

import re
from playwright.sync_api import expect


class BasePage:
    """页面基础类，封装常用 UI 操作"""

    def __init__(self, healing_page):
        self.page = healing_page

    # 导航
    def goto(self, url: str):
        """跳转到指定 URL"""
        self.page.goto(url)

    # 点击
    def click_by_role(self, role: str, name: str = ""):
        """通过 role 点击元素"""
        locator = self.page.get_by_role(role, name=name)
        locator.click()

    def click_by_text(self, text: str):
        """通过文本点击元素"""
        self.page.get_by_text(text).click()

    def click_by_selector(self, selector: str):
        """通过 CSS 选择器点击元素"""
        self.page.locator(selector).click()

    # 填写
    def fill_by_role(self, role: str, name: str, value: str):
        """通过 role 填写输入框"""
        self.page.get_by_role(role, name=name).fill(value)

    # 选择
    def check_by_label(self, label: str):
        """勾选复选框"""
        self.page.get_by_label(label).check()

    # 断言
    def assert_visible(self, text: str):
        """断言文本可见"""
        expect(self.page.get_by_text(text)).to_be_visible()

    def assert_url_contains(self, url_part: str):
        """断言 URL 包含指定内容"""
        expect(self.page).to_have_url(re.compile(url_part))

    # 等待
    def wait_for_selector(self, selector: str, timeout: int = 10000):
        """等待选择器出现"""
        self.page.wait_for_selector(selector, timeout=timeout)
'''
        base_page_path = output_path / "base_page.py"
        base_page_path.write_text(base_page_code, encoding='utf-8')

        # ===== 2. 业务 Page 类 =====
        # 将操作按语义分组为方法
        page_methods = self._group_operations_to_methods(operations, module_name)

        # 提取 import 中需要的模块
        needs_re = any('re.compile' in op or 're.' in op for op in operations)

        imports = "import re\n" if needs_re else ""
        imports += f"from .base_page import BasePage\n"

        business_page_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{page_class_name} — {module_name} 业务页面类

封装 {module_name} 模块的业务操作。
自愈功能通过 healing_page → BasePage 自动继承。
"""

{imports}


class {page_class_name}(BasePage):
    """{module_name} 业务页面类"""

{page_methods}
'''
        page_file_name = f"{module_name}_page.py"
        business_page_path = output_path / page_file_name
        business_page_path.write_text(business_page_code, encoding='utf-8')

        # ===== 3. pytest 用例 =====
        # 从 enhanced_script 提取 browser_context_args fixture
        context_fixture = ""
        if "browser_context_args" in source:
            fixture_match = re.search(
                r'@pytest\.fixture.*?browser_context_args.*?\n(?:.*?\n)*?.*?return \{.*?\}',
                source, re.DOTALL
            )
            if fixture_match:
                context_fixture = fixture_match.group(0)

        test_case_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_{module_name} — {module_name} 模块 pytest 用例

运行方式:
    pytest test_{module_name}.py --ph-strategy=SMART --ph-auto-patch-source
"""

import pytest
from .{module_name}_page import {page_class_name}

'''
        if context_fixture:
            test_case_code += context_fixture + "\n\n\n"

        test_case_code += f'''
def test_{module_name}(healing_page) -> None:
    """{module_name} 业务流程测试"""
    page = {page_class_name}(healing_page)
    page.run_full_flow()
'''

        test_file_name = f"test_{module_name}.py"
        test_case_path = output_path / test_file_name
        test_case_path.write_text(test_case_code, encoding='utf-8')

        # ===== 4. __init__.py =====
        init_path = output_path / "__init__.py"
        init_path.write_text("", encoding='utf-8')

        result = {
            "base_page": str(base_page_path),
            "business_page": str(business_page_path),
            "test_case": str(test_case_path),
        }
        print(f"✅ PO 分层生成完成:")
        print(f"   BasePage: {base_page_path}")
        print(f"   业务Page: {business_page_path}")
        print(f"   测试用例: {test_case_path}")
        return result

    def _to_camel_case(self, name: str) -> str:
        """下划线命名转驼峰: create_demand → CreateDemand"""
        return ''.join(word.capitalize() for word in name.split('_'))

    def _group_operations_to_methods(self, operations: list, module_name: str) -> str:
        """将操作列表按业务语义拆分为 PO 方法（语义定位 + 参数化）

        策略:
          1. 按 goto 分段（页面切换为天然边界）
          2. 每段再按业务操作语义细分为多个方法
          3. 选择器转换为语义定位（get_by_text + 区域相对定位）
          4. fill 操作的值提取为方法参数
        """
        if not operations:
            return f"    pass  # 待录制后生成业务方法"

        # 将 healing_page.xxx 替换为 self.page.xxx
        ops = [op.replace('healing_page.', 'self.page.') for op in operations]

        # 按 goto 分段
        segments: List[Dict] = []
        current_segment = {"ops": [], "has_goto": False, "goto_url": ""}

        for op in ops:
            if '.goto(' in op:
                if current_segment["ops"]:
                    segments.append(current_segment)
                url_match = re.search(r'\.goto\(["\']([^"\']+)', op)
                current_segment = {
                    "ops": [op],
                    "has_goto": True,
                    "goto_url": url_match.group(1) if url_match else "",
                }
            else:
                current_segment["ops"].append(op)
        if current_segment["ops"]:
            segments.append(current_segment)

        methods = []
        indent = "    "

        for i, seg in enumerate(segments):
            # 对每个段进一步按业务语义拆分为子方法
            sub_methods = self._split_segment_to_methods(seg, i, module_name)
            methods.extend(sub_methods)
            methods.append("")

        # 完整流程方法
        # 收集所有方法名和参数
        all_method_calls = []
        for i, seg in enumerate(segments):
            sub_methods = self._split_segment_to_methods(seg, i, module_name)
            for m in sub_methods:
                # 从 def 行提取方法名和参数
                def_match = re.search(r'def (\w+)\(([^)]*)\)', m)
                if def_match:
                    mname = def_match.group(1)
                    params_str = def_match.group(2).strip()
                    # 去掉 self，提取参数默认值
                    param_parts = [p.strip() for p in params_str.split(',') if p.strip() and p.strip() != 'self']
                    call_args = []
                    for p in param_parts:
                        if '=' in p:
                            pname = p.split('=')[0].strip()
                            call_args.append(f"{pname}={pname}")
                    if call_args:
                        all_method_calls.append(f"{indent}    self.{mname}({', '.join(call_args)})")
                    else:
                        all_method_calls.append(f"{indent}    self.{mname}()")

        methods.append(f"{indent}def run_full_flow(self, **kwargs):")
        methods.append(f"{indent}    \"\"\"执行 {module_name} 完整业务流程\n")
        methods.append(f"{indent}    可通过 kwargs 覆盖默认参数\"\"\"")
        for call in all_method_calls:
            methods.append(call)

        return '\n'.join(methods)

    def _split_segment_to_methods(self, segment: Dict, seg_index: int, module_name: str) -> List[str]:
        """将一个 goto 段按业务操作语义拆分为多个细粒度方法

        拆分策略：
          - goto 行 → navigate 方法
          - 连续 fill 操作 → fill_xxx 方法（值提取为参数）
          - button click + 弹窗操作 → submit/confirm 方法
          - 其他 click → 单独操作方法
        """
        ops = segment["ops"]
        indent = "    "
        methods = []

        # 先把操作按业务语义分组
        groups = self._group_by_business_action(ops, seg_index)

        for group in groups:
            method_name = group["name"]
            method_doc = group["doc"]
            method_ops = group["ops"]
            params = group.get("params", {})

            # 构建参数列表
            param_str = "self"
            if params:
                param_parts = [f'{k}="{v}"' for k, v in params.items()]
                param_str += ", " + ", ".join(param_parts)

            method_lines = []
            method_lines.append(f"{indent}def {method_name}({param_str}):")
            method_lines.append(f'{indent}    """{method_doc}"""')

            # 转换操作行：语义定位 + 参数引用
            for op in method_ops:
                converted = self._convert_to_semantic_op(op, params)
                method_lines.append(f"{indent}    {converted}")

            method_lines.append("")
            methods.append('\n'.join(method_lines))

        return methods

    def _group_by_business_action(self, ops: List[str], seg_index: int) -> List[Dict]:
        """按业务语义将操作行分组

        分组策略（三级粒度）:
          1. goto → 独立的 navigate 方法
          2. 连续的 fill + 配套的 click/check/select → 合并为一个 fill_xxx 方法
          3. 有明确业务含义的 button click（如"提交""确定""知道了"）→ 独立方法

        不拆太碎：避免每个 click 一个方法。
        """
        groups = []
        current_ops = []
        current_name = ""
        current_doc = ""
        current_params = {}
        current_fill_labels = []  # 收集 fill 的标签用于命名

        def flush():
            if current_ops:
                # 如果没有名字，根据收集的 fill 标签命名
                name = current_name
                doc = current_doc
                if not name and current_fill_labels:
                    first_label = current_fill_labels[0]
                    name = f"fill_{self._sanitize_name(first_label)}"
                    doc = f"填写{'/'.join(current_fill_labels[:3])}"
                elif not name:
                    name = f"step_{seg_index}_{len(groups) + 1}"
                    doc = current_doc or "步骤操作"
                groups.append({
                    "name": name,
                    "doc": doc,
                    "ops": current_ops[:],
                    "params": dict(current_params),
                })

        # 关键业务按钮列表（遇到这些按钮才开新组）
        BREAKPOINT_BUTTONS = [
            "提交", "确定", "知道了", "取消", "批量填充",
            "商品链接识别", "立即关联", "保存", "下一步",
        ]

        for op in ops:
            # goto → 独立方法
            if '.goto(' in op:
                flush()
                current_ops = [op]
                current_name = ""
                current_doc = ""
                current_params = {}
                current_fill_labels = []
                url_match = re.search(r'\.goto\(["\']([^"\']+)', op)
                url = url_match.group(1) if url_match else ""
                current_name = self._infer_navigate_name(url, seg_index)
                current_doc = f"导航到页面: {url[:80]}"
                flush()
                current_ops = []
                current_name = ""
                current_doc = ""
                continue

            action_type, label_text = self._extract_action_semantic(op)

            # 判断是否是断点按钮（需要开新组）
            is_breakpoint = False
            if action_type == "button_click" and label_text:
                is_breakpoint = any(bp in label_text for bp in BREAKPOINT_BUTTONS)

            if is_breakpoint:
                # 先 flush 之前的操作
                flush()
                current_ops = [op]
                current_name = self._sanitize_name(label_text)
                current_doc = f"点击「{label_text}」"
                current_params = {}
                current_fill_labels = []
                # 如果后面紧跟弹窗操作，合并进来（由下一个循环判断）
                flush()
                current_ops = []
                current_name = ""
                current_doc = ""
                continue

            # fill 操作：收集到当前组
            if action_type == "fill":
                current_ops.append(op)
                if label_text:
                    current_fill_labels.append(label_text)
                    # fill 的值提取为参数
                    value_match = re.search(r'\.fill\(["\']([^"\']*)["\']\)', op)
                    if value_match:
                        param_name = self._sanitize_name(label_text)
                        current_params[param_name] = value_match.group(1)
                # 更新方法名（用第一个 fill 标签）
                if not current_name and current_fill_labels:
                    current_name = f"fill_{self._sanitize_name(current_fill_labels[0])}"
                    current_doc = f"填写{'/'.join(current_fill_labels[:3])}"
                continue

            # click / check / select：合并到当前组（配套操作）
            current_ops.append(op)
            if action_type == "check" and label_text:
                if not current_name:
                    current_name = f"check_{self._sanitize_name(label_text)}"
                    current_doc = f"勾选{label_text}"
            elif action_type == "click" and label_text:
                # 非 button 的 click（如文本点击展开选项），也合并
                if not current_name:
                    current_name = f"click_{self._sanitize_name(label_text)}"
                    current_doc = f"点击{label_text}"

        flush()
        return groups

    def _extract_action_semantic(self, op: str) -> tuple:
        """从操作行提取操作类型和语义标签

        Returns:
            (action_type, label_text)
            action_type: "fill" | "button_click" | "click" | "select" | "check" | "navigate" | "other"
            label_text: 人可读的标签文本
        """
        # goto
        if '.goto(' in op:
            return ("navigate", "")

        # fill — 从 name= 或 get_by_text 提取标签
        if '.fill(' in op:
            label = self._extract_label_from_locator(op)
            return ("fill", label)

        # check
        if '.check(' in op:
            label = self._extract_label_from_locator(op)
            return ("check", label)

        # select_option
        if '.select_option(' in op:
            return ("select", "")

        # click — 区分按钮点击和普通点击
        if '.click(' in op:
            label = self._extract_label_from_locator(op)
            # 检查是否是按钮/链接/菜单项
            if any(kw in op for kw in ['role="button"', 'get_by_role("button"', 'get_by_text']):
                return ("button_click", label)
            return ("click", label)

        return ("other", "")

    def _extract_label_from_locator(self, op: str) -> str:
        """从定位器中提取人可读的标签文本

        优先级:
          1. get_by_role(xxx, name="标签") → "标签"
          2. get_by_text("标签") → "标签"
          3. get_by_label("标签") → "标签"
          4. CSS/ID 选择器 → 空字符串（无法推断语义）
        """
        # get_by_role(xxx, name="标签")
        role_name_match = re.search(r'get_by_role\(\s*\w+\s*,\s*name="([^"]+)"', op)
        if role_name_match:
            return role_name_match.group(1)

        # get_by_text("标签")
        text_match = re.search(r'get_by_text\(["\']([^"\']+)["\']\)', op)
        if text_match:
            return text_match.group(1)

        # get_by_label("标签")
        label_match = re.search(r'get_by_label\(["\']([^"\']+)["\']\)', op)
        if label_match:
            return label_match.group(1)

        return ""

    def _convert_to_semantic_op(self, op: str, params: Dict) -> str:
        """将 codegen 原始操作转换为语义定位版本

        策略:
          - get_by_role / get_by_text / get_by_label → 保留（已经是语义定位）
          - locator("css选择器") → 尝试转为 get_by_text 区域定位
          - fill 的值 → 替换为参数引用
        """
        result = op

        # 如果已经是语义定位器（get_by_role, get_by_text, get_by_label），保留
        if any(kw in op for kw in ['get_by_role(', 'get_by_text(', 'get_by_label(']):
            # 只需处理 fill 值的参数化
            result = self._parametrize_fill_value(result, params)
            return result

        # CSS/ID 定位器 → 尝试语义转换
        # locator("#xxx") 或 locator("css选择器")
        locator_match = re.search(r'self\.page\.locator\("([^"]+)"\)', op)
        if locator_match:
            css_selector = locator_match.group(1)
            # 如果操作包含 .get_by_text 或有 name 参数的复合定位器，保留
            if 'get_by_text(' in op or 'name=' in op:
                result = self._parametrize_fill_value(result, params)
                return result

            # 纯 CSS 定位器无法自动转语义，保留原样但标注
            result = self._parametrize_fill_value(result, params)
            return result

        # 其他情况：保留原样 + 参数化 fill 值
        result = self._parametrize_fill_value(result, params)
        return result

    def _parametrize_fill_value(self, op: str, params: Dict) -> str:
        """将 fill 操作的硬编码值替换为参数引用"""
        if '.fill(' not in op:
            return op

        # 找 fill 的值
        fill_match = re.search(r'\.fill\(["\']([^"\']*)["\']\)', op)
        if not fill_match:
            return op

        fill_value = fill_match.group(1)
        if not fill_value:
            return op

        # 检查值是否匹配某个参数的默认值
        for param_name, default_val in params.items():
            if fill_value == default_val:
                # 替换为参数引用
                result = op.replace(f'.fill("{fill_value}")', f'.fill({param_name})')
                result = result.replace(f".fill('{fill_value}')", f".fill({param_name})")
                return result

        return op

    def _infer_navigate_name(self, url: str, seg_index: int) -> str:
        """根据 URL 推断导航方法名"""
        url_method_map = {
            "overview": "navigate_to_overview",
            "demand_front": "navigate_to_demand",
            "waitReview": "navigate_to_review",
            "demand/list": "navigate_to_demand_list",
            "demand/detail": "navigate_to_demand_detail",
            "demand/save": "navigate_to_save_demand",
        }
        for key, name in url_method_map.items():
            if key in url:
                return name

        if seg_index == 0:
            return "navigate_to_page"

        return f"navigate_step_{seg_index + 1}"

    def _sanitize_name(self, text: str) -> str:
        """将中文/特殊字符标签转为可用的方法名/参数名

        例如: "* 需求单名称" → "demand_name"
              "商品链接识别" → "product_link_detect"
        """
        # 去掉前缀标记
        text = text.lstrip("* ").strip()

        # 中文关键词 → 英文映射
        cn_to_en = {
            "需求单名称": "demand_name",
            "需求名称": "demand_name",
            "经费项目号": "fund_code",
            "费用类型": "expense_type",
            "预算科目": "budget_type",
            "经办人": "manager_name",
            "采购实施主体": "purchase_entity",
            "是否需要指标编码": "need_target_code",
            "是否上报建议书": "need_proposal",
            "采购方式": "purchase_method",
            "执行方式": "exec_method",
            "商品链接识别": "add_product_by_url",
            "商品链接": "product_url",
            "请输入链接": "product_url",
            "立即关联": "bind_budget",
            "批量填充": "batch_fill",
            "提交": "submit_demand",
            "确定": "confirm",
            "知道了": "confirm_submit",
            "取消": "cancel",
            "请选择": "select",
            "采购中心": "purchase_center",
            "分散采购": "decentralized_purchase",
            "自行采购": "self_purchase",
            "办公用品": "office_supplies",
            "办公费": "office_expense",
            "审核人": "auditor_name",
            "选择审核人": "select_auditor",
            "请输入后选择": "search_and_select",
            "我提交的需求": "my_demands",
            "请输入": "search_keyword",
            "采购需求管理": "demand_management",
            "采购需求申报": "demand_declaration",
        }

        # 精确匹配
        if text in cn_to_en:
            return cn_to_en[text]

        # 包含匹配
        for cn, en in cn_to_en.items():
            if cn in text:
                return en

        # 兜底：去掉特殊字符
        name = re.sub(r'[^\w]', '_', text)
        name = re.sub(r'_+', '_', name).strip('_')
        return name if name else "value"

    def _infer_method_name(self, index: int, segment: Dict, module_name: str) -> str:
        """根据段内容推断方法名"""
        url = segment.get("goto_url", "")

        if index == 0 and ("login" in url or "user-login" in url):
            return "login"

        url_page_map = {
            "overview": "navigate_overview",
            "demand_front": "navigate_demand",
            "waitReview": "navigate_review",
            "demand/list": "navigate_demand_list",
            "demand/detail": "navigate_demand_detail",
            "demand/save": "submit_demand",
            "workflow/execute": "submit_workflow",
        }
        for key, name in url_page_map.items():
            if key in url:
                return name

        ops_text = " ".join(segment["ops"])
        action_map = {
            "fill": "fill_form",
            "需求单名称": "fill_demand_form",
            "采购需求申报": "create_demand",
            "从购物车选品": "select_products",
            "审核": "review_submit",
            "确定": "confirm_action",
            "立即关联": "bind_relation",
        }
        for key, name in action_map.items():
            if key in ops_text:
                return name

        return f"step_{index + 1}"

    def _infer_method_doc(self, index: int, segment: Dict, module_name: str) -> str:
        """推断方法文档字符串"""
        url = segment.get("goto_url", "")
        ops = segment.get("ops", [])

        if index == 0 and ("login" in url or "user-login" in url):
            return "登录系统"

        if ".goto(" in ops[0] if ops else "":
            return f"导航到页面: {url[:60]}"

        ops_text = " ".join(ops)
        if "fill" in ops_text:
            return "填写表单"
        if "click" in ops_text and "审核" in ops_text:
            return "提交审核"
        if "click" in ops_text:
            return "执行操作"

        return f"{module_name} 步骤 {index + 1}"

    def _clean_noise(self, source: str) -> str:
        """清洗 codegen 录制噪音，生成精简版脚本

        安全规则（只在条件完全满足时才删除，绝不误杀）:
          规则1: 同一选择器的 click → fill/click 序列中，fill 前的 click 删除
                 条件: 选择器字符串完全匹配 + click 紧邻 fill
          规则2: 同一选择器的连续 fill，只保留最后一个
                 条件: 选择器字符串完全匹配 + 中间只有 press
          规则3: 夹在两个同选择器 fill 之间的 press 删除
                 条件: press 前后的 fill 选择器完全匹配

        不清洗的模式（保留）:
          - 不同选择器的 click/fill（是不同字段的操作）
          - click 后没有 fill（是真正的点击操作）
          - check/select_option 操作
          - 非 fill 前的 press（如 press("Enter") 提交表单）
        """
        lines = source.split('\n')
        # 解析操作行：提取选择器 + 操作类型
        parsed = []
        for i, line in enumerate(lines):
            stripped = line.strip()
            if not stripped.startswith('healing_page.') or stripped.startswith('#'):
                parsed.append({"line_idx": i, "action": None, "selector": None, "keep": True})
                continue

            action, selector = self._parse_action_line(stripped)
            parsed.append({"line_idx": i, "action": action, "selector": selector, "keep": True})

        # 规则1: fill/click 前的同选择器 click 删除
        for i in range(1, len(parsed)):
            curr = parsed[i]
            prev = parsed[i - 1]
            if (curr["action"] in ("fill", "click") and
                prev["action"] == "click" and
                curr["selector"] and prev["selector"] and
                curr["selector"] == prev["selector"]):
                prev["keep"] = False

        # 规则2+3: 同选择器的连续 fill + 夹在中间的 press，只保留最后一个 fill
        i = 0
        while i < len(parsed):
            if parsed[i]["action"] != "fill" or not parsed[i]["selector"]:
                i += 1
                continue

            # 找到连续的同选择器 fill/press 序列
            selector = parsed[i]["selector"]
            sequence_start = i
            j = i + 1
            while j < len(parsed):
                if (parsed[j]["action"] == "fill" and parsed[j]["selector"] == selector):
                    j += 1
                elif (parsed[j]["action"] == "press" and parsed[j]["selector"] == selector):
                    j += 1
                else:
                    break

            sequence = parsed[sequence_start:j]
            # 如果序列中有多个 fill，只保留最后一个
            fill_indices = [k for k, p in enumerate(sequence) if p["action"] == "fill"]
            if len(fill_indices) > 1:
                # 标记最后一个 fill 之前的所有 fill 和 press 为不保留
                last_fill = fill_indices[-1]
                for k in range(last_fill):
                    sequence[k]["keep"] = False

            i = j

        # 应用保留/删除
        result_lines = []
        removed_count = 0
        for p in parsed:
            if p["keep"]:
                result_lines.append(lines[p["line_idx"]])
            else:
                removed_count += 1

        if removed_count > 0:
            print(f"   🧹 脚本清洗: 移除 {removed_count} 行录制噪音")

        return '\n'.join(result_lines)

    def _parse_action_line(self, line: str) -> tuple:
        """解析 healing_page 操作行，提取 (action, selector)

        Returns:
            (action, selector) 如 ("fill", 'get_by_role("textbox", name="xxx")')
            无法解析时返回 (None, None)
        """
        # 匹配 healing_page.SELECTOR.ACTION(...) 或 healing_page.SELECTOR.COMPOSED.ACTION(...)
        # 先尝试提取最后的操作方法
        action = None
        for act in ["fill", "click", "press", "check", "select_option", "dblclick", "hover"]:
            pattern = rf'\.{act}\('
            if re.search(pattern, line):
                action = act
                break

        if not action:
            return (None, None)

        # 提取选择器部分：healing_page.xxx.yyy.action 中的 healing_page.xxx.yyy
        # 从 healing_page. 后面到 .action( 之前
        action_pattern = rf'\.{action}\('
        match = re.search(rf'healing_page\.(.+?){action_pattern}', line)
        if match:
            selector = "healing_page." + match.group(1)
            return (action, selector)

        return (action, None)

    def _inject_after_last_action(self, source: str, block: str) -> str:
        """在最后一个 healing_page.xxx 操作行之后注入代码块"""
        lines = source.split('\n')
        last_action_idx = -1

        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith('healing_page.') and not stripped.startswith('#'):
                last_action_idx = i

        if last_action_idx >= 0:
            lines.insert(last_action_idx + 1, block)
        else:
            # 找不到操作行，插入到文件末尾
            lines.append(block)

        return '\n'.join(lines)

    # ── 表单填写经验沉淀 ────────────────────────────────────

    def _apply_form_experience(self, source: str) -> str:
        """将表单填写经验自动应用到 enhanced_script

        经验规则（从实际验证中总结）:

        规则1 - goto 加超时:
          codegen 产出: healing_page.goto("url")
          优化后:       healing_page.goto("url", timeout=30000, wait_until="domcontentloaded")
          原因: 测试环境页面加载慢，默认 30s 超时不够

        规则2 - goto 后不加 networkidle:
          不使用 wait_for_load_state("networkidle")
          原因: 测试环境有轮询请求，networkidle 永远达不到
          替代: 等页面关键元素出现

        规则3 - 弹窗后操作加等待:
          点击"提交""确定""审核"等按钮后，下一个操作前加 time.sleep(1)
          原因: 弹窗关闭有动画，下个弹窗可能还没渲染完

        规则4 - 保留录制的原始选择器:
          codegen 录出来的选择器（CSS/ID）是最可靠的
          不要尝试用 get_by_text 替换（同一个文本页面出现多次会选错）

        规则5 - 下拉选择保留原始流程:
          录制的 click → option 两步不要合并
          不要用 _wait_and_select_option 替换（可能选错下拉框）
        """
        # 规则1: goto 加超时和 domcontentloaded
        source = re.sub(
            r'healing_page\.goto\(("([^"]+)")\)',
            r'healing_page.goto(\1, timeout=30000, wait_until="domcontentloaded")',
            source,
        )
        # 已经有 timeout 参数的不重复加
        source = re.sub(
            r'healing_page\.goto\(("([^"]+)", timeout=(\d+), wait_until="domcontentloaded"), timeout=(\d+), wait_until="domcontentloaded"\)',
            r'healing_page.goto(\1)',
            source,
        )

        return source
