#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ScriptTransformer — 将 codegen 输出转换为 playwright-healer 兼容格式

核心转换:
  1. page → healing_page（healer pytest fixture）
  2. 类型注解 Page → 删除（healer 用自注册 fixture）
  3. 注入断言桩（AI 后续填充）
  4. 注入变量提取桩（{{demand_id}} 模板）

关键：替换逻辑必须精确，避免双重替换（healing_page→healing_healing_page）
"""

import re
from pathlib import Path
from typing import List, Optional, Dict


class ScriptTransformer:
    """将 codegen 生成的脚本转换为 healer 兼容格式"""

    def transform(
        self,
        input_path: str,
        output_path: str,
        module_name: str = "",
        extract_vars: Optional[List[Dict]] = None,
        assert_stubs: Optional[List[Dict]] = None,
    ) -> str:
        """转换脚本

        Args:
            input_path: codegen 生成的原始脚本路径
            output_path: 转换后的增强脚本路径
            module_name: 模块名称
            extract_vars: 变量提取桩列表
            assert_stubs: 断言桩列表

        Returns:
            str: 转换后的脚本内容
        """
        with open(input_path, 'r', encoding='utf-8') as f:
            source = f.read()

        # 用占位符保护已替换的内容，避免双重替换
        PLACEHOLDER = "\x00HEALING_PAGE\x00"

        # 1. 替换函数签名中的 page 参数
        #    def test_xxx(page: Page) → def test_xxx(healing_page)
        source = re.sub(
            r'def (test_\w+)\(\s*page(?:\s*:\s*Page)?\s*\)',
            rf'def \1({PLACEHOLDER})',
            source,
        )

        # 2. 替换 expect(page) → expect(PLACEHOLDER)
        source = re.sub(r'\bexpect\(page\)', rf'expect({PLACEHOLDER})', source)
        source = re.sub(r'\bexpect\(page\b', rf'expect({PLACEHOLDER}', source)

        # 3. 替换 page.xxx 操作调用 → PLACEHOLDER.xxx（核心替换）
        #    只匹配 \bpage\. 避免匹配 import 中的 Page
        source = re.sub(r'\bpage\.', f'{PLACEHOLDER}.', source)

        # 4. 删除 page = context.new_page() 行
        source = re.sub(r'\s*page\s*=\s*context\.new_page\(\).*\n?', '', source)

        # 5. 处理 import 行：移除 Page 类型，保留其他 import
        def _fix_import_line(match):
            """处理 from playwright.sync_api import ... 这行"""
            full_line = match.group(0)
            # 提取 import 列表
            import_match = re.search(r'from\s+playwright\.sync_api\s+import\s+(.*)', full_line)
            if not import_match:
                return ''
            imports_str = import_match.group(1)
            # 分割各个 import 项
            items = [i.strip() for i in imports_str.split(',')]
            # 移除 Page
            items = [i for i in items if i and i != 'Page']
            if not items:
                return ''
            return f'from playwright.sync_api import {", ".join(items)}\n'

        source = re.sub(
            r'from\s+playwright\.sync_api\s+import\s+.*?Page.*?\n',
            _fix_import_line,
            source,
            count=1,
        )

        # 6. 现在安全地把占位符替换为 healing_page
        source = source.replace(PLACEHOLDER, 'healing_page')

        # 6b. 注入 context/browser 别名（codegen 脚本可能引用这些变量）
        # healing_page 实际上就是一个 Page 对象，没有 context/browser
        # 如果脚本中有 context.xxx 或 browser.xxx 的调用，需要提供别名
        has_context_ref = bool(re.search(r'\bcontext\.', source))
        has_browser_ref = bool(re.search(r'\bbrowser\.', source))
        if has_context_ref or has_browser_ref:
            alias_inject = ""
            if has_context_ref:
                alias_inject += "    context = healing_page.context\n"
            if has_browser_ref:
                alias_inject += "    browser = healing_page.context.browser\n"
            # 注入到 def test_xxx(healing_page): 下一行
            source = re.sub(
                r'(def test_\w+\(healing_page\)\s*:\n)',
                rf'\1{alias_inject}',
                source,
                count=1,
            )

        # 7. 注入模块头部说明
        # 在头部插入 import datetime（用于时间戳变量）
        ts_import = "from datetime import datetime\n"
        # 在 def test_xxx 之前插入时间戳变量定义
        ts_var = '    _test_ts = datetime.now().strftime("%Y%m%d%H%M%S")\n'

        header = f'''"""
Auto-generated by smart-test-automation
Module: {module_name}
Self-healing enabled via playwright-healer (healing_page fixture)

Run with:
    pytest {Path(output_path).name} --ph-strategy=SMART --ph-auto-patch-source
"""

'''
        # 删除原始文件的 docstring（如果有）
        source = re.sub(r'^""".*?"""', '', source, count=1, flags=re.DOTALL)
        source = header + source.strip() + '\n'

        # 7b. 在 import 区域后插入 datetime import
        # 找到最后一个 import 行，在其后插入
        import_lines = list(re.finditer(r'^(?:from\s+[\w.]+\s+import\s+.*|import\s+.*)$', source, re.MULTILINE))
        if import_lines:
            last_import = import_lines[-1]
            source = source[:last_import.end()] + '\n' + ts_import + source[last_import.end():]

        # 7c. 在 def test_xxx(healing_page): 后插入时间戳变量
        source = re.sub(
            r'(def test_\w+\(healing_page\)(?:\s*->\s*[^:]+)?\s*:\n)',
            rf'\1{ts_var}',
            source,
            count=1,
        )

        # 8. 收集所有要注入的代码块，然后一次性注入（避免多次插入位置错乱）
        injection_blocks = []

        # 8a. 变量提取桩
        if extract_vars:
            extract_block = "    # === 变量提取 ===\n"
            extract_block += "    extracted_vars = {}\n"
            for var in extract_vars:
                var_name = var.get("name", "")
                from_api = var.get("from_api", "")
                from_field = var.get("from_field", "")
                extract_block += f"    # TODO: extracted_vars['{var_name}'] = 从API响应提取 ({from_api}.{from_field})\n"
            extract_block += "    # 变量将在编排引擎中自动注入到后续模块\n"
            injection_blocks.append(extract_block)

        # 8b. 断言桩
        assert_block = "    # === 三层断言 ===\n"
        if assert_stubs:
            for stub in assert_stubs:
                layer = stub.get("layer", "ui")
                desc = stub.get("description", "")
                if layer == "ui":
                    assert_block += f"    # UI断言: {desc}\n"
                    assert_block += f"    # expect(healing_page.get_by_text('{desc}')).to_be_visible()\n"
                elif layer == "api":
                    assert_block += f"    # API断言: {desc}\n"
                    assert_block += f"    # assert api_response['code'] == 0\n"
                elif layer == "db":
                    assert_block += f"    # DB断言: {desc}\n"
                    assert_block += f"    # assert db_query_result is not None\n"
        else:
            assert_block += "    # UI断言: 操作成功提示可见\n"
            assert_block += "    # expect(healing_page.get_by_text('成功')).to_be_visible()\n"
            assert_block += "    # API断言: 关键接口返回 code=0\n"
            assert_block += "    # DB断言: 数据记录已写入（MySQL不可达则跳过）\n"
        injection_blocks.append(assert_block)

        # 一次性在最后一个 healing_page.xxx 操作行之后注入所有代码块
        source = self._inject_after_last_action(source, '\n'.join(injection_blocks))

        # 9. 写入输出文件
        output_dir = Path(output_path).parent
        output_dir.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(source)

        print(f"✅ 转换完成: {input_path} → {output_path}")
        return source

    def generate_po_layers(
        self,
        enhanced_script_path: str,
        output_dir: str,
        module_name: str,
        page_class_name: str = "",
    ) -> Dict[str, str]:
        """将 enhanced_script 拆分为 PO 三层结构

        生成:
          - base_page.py: BasePage 基础类（封装 healing_page 常用操作）
          - {module}_page.py: 业务 Page 类（封装业务操作方法）
          - test_{module}.py: pytest 用例（调用业务 Page）

        Args:
            enhanced_script_path: enhanced_script.py 路径
            output_dir: 输出目录
            module_name: 模块名
            page_class_name: 自定义 Page 类名（默认 CamelCase 转换）

        Returns:
            Dict[str, str]: 生成的文件路径
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # 读取 enhanced_script 提取操作
        with open(enhanced_script_path, 'r', encoding='utf-8') as f:
            source = f.read()

        # 提取 healing_page 操作行
        operations = []
        for line in source.split('\n'):
            stripped = line.strip()
            if stripped.startswith('healing_page.') and not stripped.startswith('#'):
                operations.append(stripped)

        if not page_class_name:
            page_class_name = self._to_camel_case(module_name) + "Page"

        # ===== 1. BasePage =====
        base_page_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BasePage — 页面基础类

封装 healing_page 常用操作，所有业务 Page 类继承此类。
自愈功能由 playwright-healer 的 healing_page fixture 自动提供。
"""

from playwright.sync_api import expect


class BasePage:
    """页面基础类，封装常用 UI 操作"""

    def __init__(self, healing_page):
        self.page = healing_page

    # --- 导航 ---
    def goto(self, url: str):
        """跳转到指定 URL"""
        self.page.goto(url)

    # --- 点击 ---
    def click_by_role(self, role: str, name: str = ""):
        """通过 role 点击元素"""
        locator = self.page.get_by_role(role, name=name)
        locator.click()

    def click_by_text(self, text: str):
        """通过文本点击元素"""
        self.page.get_by_text(text).click()

    def click_by_selector(self, selector: str):
        """通过 CSS 选择器点击元素"""
        self.page.locator(selector).click()

    # --- 填写 ---
    def fill_by_role(self, role: str, name: str, value: str):
        """通过 role 填写输入框"""
        self.page.get_by_role(role, name=name).fill(value)

    # --- 选择 ---
    def check_by_label(self, label: str):
        """勾选复选框"""
        self.page.get_by_label(label).check()

    # --- 断言 ---
    def assert_visible(self, text: str):
        """断言文本可见"""
        expect(self.page.get_by_text(text)).to_be_visible()

    def assert_url_contains(self, url_part: str):
        """断言 URL 包含指定内容"""
        expect(self.page).to_have_url(re.compile(url_part))

    # --- 等待 ---
    def wait_for_selector(self, selector: str, timeout: int = 10000):
        """等待选择器出现"""
        self.page.wait_for_selector(selector, timeout=timeout)
'''
        base_page_path = output_path / "base_page.py"
        base_page_path.write_text(base_page_code, encoding='utf-8')

        # ===== 2. 业务 Page 类 =====
        # 将操作按语义分组为方法
        page_methods = self._group_operations_to_methods(operations, module_name)

        # 提取 import 中需要的模块
        needs_re = any('re.compile' in op or 're.' in op for op in operations)

        imports = "import re\n" if needs_re else ""
        imports += f"from .base_page import BasePage\n"

        business_page_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{page_class_name} — {module_name} 业务页面类

封装 {module_name} 模块的业务操作。
自愈功能通过 healing_page → BasePage 自动继承。
"""

{imports}


class {page_class_name}(BasePage):
    """{module_name} 业务页面类"""

{page_methods}
'''
        page_file_name = f"{module_name}_page.py"
        business_page_path = output_path / page_file_name
        business_page_path.write_text(business_page_code, encoding='utf-8')

        # ===== 3. pytest 用例 =====
        # 从 enhanced_script 提取 browser_context_args fixture
        context_fixture = ""
        if "browser_context_args" in source:
            fixture_match = re.search(
                r'@pytest\.fixture.*?browser_context_args.*?\n(?:.*?\n)*?.*?return \{.*?\}',
                source, re.DOTALL
            )
            if fixture_match:
                context_fixture = fixture_match.group(0)

        test_case_code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_{module_name} — {module_name} 模块 pytest 用例

运行方式:
    pytest test_{module_name}.py --ph-strategy=SMART --ph-auto-patch-source
"""

import pytest
from .{module_name}_page import {page_class_name}

'''
        if context_fixture:
            test_case_code += context_fixture + "\n\n\n"

        test_case_code += f'''
def test_{module_name}(healing_page) -> None:
    """{module_name} 业务流程测试"""
    page = {page_class_name}(healing_page)
    page.run_full_flow()
'''

        test_file_name = f"test_{module_name}.py"
        test_case_path = output_path / test_file_name
        test_case_path.write_text(test_case_code, encoding='utf-8')

        # ===== 4. __init__.py =====
        init_path = output_path / "__init__.py"
        init_path.write_text("", encoding='utf-8')

        result = {
            "base_page": str(base_page_path),
            "business_page": str(business_page_path),
            "test_case": str(test_case_path),
        }
        print(f"✅ PO 分层生成完成:")
        print(f"   BasePage: {base_page_path}")
        print(f"   业务Page: {business_page_path}")
        print(f"   测试用例: {test_case_path}")
        return result

    def _to_camel_case(self, name: str) -> str:
        """下划线命名转驼峰: create_demand → CreateDemand"""
        return ''.join(word.capitalize() for word in name.split('_'))

    def _group_operations_to_methods(self, operations: list, module_name: str) -> str:
        """将操作列表按语义分组为 Page 类方法"""
        if not operations:
            return f"    pass  # 待录制后生成业务方法"

        # 简单策略: 按导航/登录/业务/提交 分组
        nav_ops = []
        login_ops = []
        biz_ops = []

        for op in operations:
            if '.goto(' in op:
                nav_ops.append(op.replace('healing_page.', 'self.page.'))
            elif 'login' in op.lower() or '登 录' in op or '密码' in op or '用户名' in op:
                login_ops.append(op.replace('healing_page.', 'self.page.'))
            else:
                biz_ops.append(op.replace('healing_page.', 'self.page.'))

        methods = []
        indent = "    "

        # 登录方法
        if login_ops:
            methods.append(f"{indent}def login(self):")
            methods.append(f"{indent}    \"\"\"执行登录操作\"\"\"")
            for op in login_ops:
                methods.append(f"{indent}    {op}")
            methods.append("")

        # 导航方法
        if nav_ops:
            methods.append(f"{indent}def navigate_to_page(self):")
            methods.append(f"{indent}    \"\"\"导航到业务页面\"\"\"")
            for op in nav_ops:
                methods.append(f"{indent}    {op}")
            methods.append("")

        # 业务操作方法
        if biz_ops:
            methods.append(f"{indent}def do_business_action(self):")
            methods.append(f"{indent}    \"\"\"执行 {module_name} 核心业务操作\"\"\"")
            for op in biz_ops:
                methods.append(f"{indent}    {op}")
            methods.append("")

        # 完整流程方法
        methods.append(f"{indent}def run_full_flow(self):")
        methods.append(f"{indent}    \"\"\"执行 {module_name} 完整业务流程\"\"\"")
        if login_ops:
            methods.append(f"{indent}    self.login()")
        if nav_ops:
            methods.append(f"{indent}    self.navigate_to_page()")
        if biz_ops:
            methods.append(f"{indent}    self.do_business_action()")

        return '\n'.join(methods)

    def _inject_after_last_action(self, source: str, block: str) -> str:
        """在最后一个 healing_page.xxx 操作行之后注入代码块"""
        lines = source.split('\n')
        last_action_idx = -1

        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith('healing_page.') and not stripped.startswith('#'):
                last_action_idx = i

        if last_action_idx >= 0:
            lines.insert(last_action_idx + 1, block)
        else:
            # 找不到操作行，插入到文件末尾
            lines.append(block)

        return '\n'.join(lines)
